name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo pip install black
          sudo pip install pytest
          sudo pip install PyQt5
          sudo pip install pytest-qt

      - name: Check codestyle
        run: black . --check --diff

      - name: test
        run: make test

