name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      GKSwstype: "100"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install pytest
          pip install PyQt5
          pip install pytest-qt
          sudo apt-get update
          sudo apt-get install libxcb-xinerama0-dev



      - name: Check codestyle
        run: black . --check --diff

      - name: test
        run: make test

