name: Build

on: push


jobs:
  build:
    runs-on: linux


    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install pytest
          pip install PyQt5
          pip install pytest-qt

      - name: Check codestyle
        run: black . --check --diff

      - name: test
        run: make test

