name: Build

on: push

env:
  DISPLAY: ':99'

jobs:
  build:
    runs-on: ubuntu-20.04


    steps:
      - uses: actions/checkout@v2

      - name: Xvfb install and run
        run: |
          sudo apt-get install -y xvfb
          Xvfb -ac ${{ env.DISPLAY }} -screen 0 1280x780x24 &

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install pytest
          pip install PyQt5
          pip install pytest-qt




      - name: Check codestyle
        run: black . --check --diff

      - name: test
        run: make test

